### ISSUE TITLE
Notification for user not having enough resource

### ISSUE THREAD

**Issue by yiochen** [yiochen/CSE381#103]
User will feel confused when they click on the button to upgrade soldier but nothing happen. We also need to tell user when soldier creation stops because of the lack of resource

**Comment by Ohmstyle64** [comment]
Do you think that we should have the soldiers building toggle off when they run out of resources? In my last commit of #102  I added a green icon of a soldier to indicate that soldiers were being trained.

**Comment by yiochen** [comment]
Added NotificationBoard Prefab. It is a singleton, to publish a notification, call
`NotificationBoardScript.Instance.PushMessage("Hello world")` for example. There is a maximum character count of 38 characters
