### ISSUE TITLE
Script naming convention

### ISSUE THREAD

**Issue by yiochen** [yiochen/CSE381#23]
I feel I have been following this convention when creating scripts.  
If the script is going to be attached to a game object, name it with `script` at the end.   
If the script is for other use, such as static class, singleton, abstract class, constant, name it without `script`. @Ohmstyle64 How do you like this convention

**Comment by Ohmstyle64** [comment]
Makes sense to me.

While we are on the topic of classes, should the ManagerScript implement the Singleton class? I only see us having 1 of those per scene.

**Comment by yiochen** [comment]
Make sense
