### ISSUE TITLE
Ship Launching

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#35]
When a ship is moving along a path we can cause the ship to reset it's position back to the launching planet. This happens when you try launching the ship a second time while it's moving.

I see 2 solutions to this:

1. We only allow 1 ship to travel be per player to be traveling on a path at once (player and enemy at same time is fine). This would be accomplished by just checking if there is a moving ship before launching the ship.
2. We allow multiple ships to be launched (they need to be created first of course). This would be be accomplished by removing the ShipScript reference in the ships array.

**Comment by yiochen** [comment]
Or 3rd solution:  It's a feature

**Comment by yiochen** [comment]
I think when the ship is launched, the planet script should remove the reference to the ship immediately. I will do that now
