### ISSUE TITLE
Ship not loading unit

### ISSUE THREAD

**Issue by yiochen** [yiochen/CSE381#36]
Currently ship will not load units because before the ship is launched, it is not enabled. The Update method will not be called, thus causing the ship not loading.   
One way to solve it is to set it as enabled once is created. But we also want to hide it. So just move it to a random place that is out of view.

**Comment by Ohmstyle64** [comment]
I got to this to work by just adding a Mesh Renderer to the NormalShip. If you can add that to your intro.unity scene on your next commit.
