### ISSUE TITLE
Tutorial Stages

### ISSUE THREAD

**Issue by yiochen** [yiochen/CSE381#48]
Add couple very simple stages to demonstrate the game play.  
tutorial1 --**How to launch ship**: two planets, one player, one enemy, player has ship loaded, enemy has no unit
tutorial2 --**How to build ship**:  three planets, one player, one neutral, one enemy, enemy has no unit

**Comment by Ohmstyle64** [comment]
2 Tutorial stages.
1 teaching them the importance of resources
1 teaching them how to build soldiers.
