### ISSUE TITLE
create soldier button

### ISSUE THREAD

**Issue by yiochen** [yiochen/CSE381#51]

**Comment by yiochen** [comment]
currently the toggle will call the function (`createSoldier`) Every frame. But for some reason, the number of soldier will not increase.

**Comment by Ohmstyle64** [comment]
The issue was that the player had no resources to produce soldiers or engineers. The players (and enemies) resource's exist globally inside the GameManager class. I changed those values to 200 for the player and for lvl1 the enemy has 100 resources.
