### ISSUE TITLE
Combat Visual

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#59]
When a planet is contested we have a visual indication that there is a battle with the particle effects. We should also introduce a meter/visual that indicates who is winning the battle.

Here is an example of an idea I have that would be displayed over the Planet.

![combatmeter](https://cloud.githubusercontent.com/assets/4655563/20855759/84a4a138-b8cf-11e6-9dd7-961a72fb8282.png)

**Comment by Ohmstyle64** [comment]
@yiochen  let me know what you think about the combat bar.

**Comment by yiochen** [comment]
They look great
