### ISSUE TITLE
Ranking System Changes

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#60]
The ranking system should be changed as follows:

1. The system will rank planet strength in absolute terms rather then relative. For example, each skull represents 50 enemy soldiers.
2. We can have the strength of all enemy planets always shown, instead of requiring the selection of a neighboring planet.

**Comment by Ohmstyle64** [comment]
I'm thinking about the idea of 50 soldiers representing a single skull and then in implementation we run the risk of having too many skulls on a planet, unless we do some scaling of skull sizes. What about a cap on the total units on a planet?

This adds some depth to the game:
1. Players would want to expand so they can increase the total number of soldiers.
2. For players with less total planets then the enemy, merely defending a choke isn't as effective because an enemy can send more waves of units and win by attrition.

Thoughts?

**Comment by yiochen** [comment]
I have been thinking about limiting the units on the same planet. But this cause a problem. When a ship arrives, it might happen that only a portion of the soldier can get off.

**Comment by Ohmstyle64** [comment]
I think we can solve this with 2 changes two together:
1. Automatically unloading of surplus units back onto the planet, when launching a ship.
Surplus = (soldiers on planet + soldiers on other incoming ship + soldiers you intend to launch) - soldier cap
2. Preventing the launch of a ship if 0 soldiers can be sent.

**Comment by Ohmstyle64** [comment]
Another idea is to limit the total number of units globally

**Comment by yiochen** [comment]
We don't know which planet is the incoming planet before launching, so we don't know the surplus.

**Comment by Ohmstyle64** [comment]
We can cycle through the shipscontainer and look at the target planet on each ship

**Comment by yiochen** [comment]
How do you think about the purple star idea I sent to you on hangout. If more than 5*, change the star to purple, and keep it at 5*

**Comment by yiochen** [comment]
I was talking about one star represent certain unit, say 50. Player's rank is yellow, enemy's rank is blue. When a planet has more than 50x5 units, still show 5 stars, but change the color to purple, meaning this is a very tough planet, invade it at your own risk

**Comment by Ohmstyle64** [comment]
I think that should work. So strategically, getting purple stars worth of units would mean that you had spent a decent amount of time preparing because we want it to be a significant force in the game.

**Comment by Ohmstyle64** [comment]
@yiochen  looking to close this if you like these changes.
