### ISSUE TITLE
Ship Ownership Visual

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#61]
When playing the game it can be difficult to keep track of enemy / player ships. There should be a visual indication when a ship is traveling about it's ownership. For example, the player ship will have a yellow highlight and the enemy ship will have a blue highlight.

**Comment by yiochen** [comment]
A simple solution to this. Different ship models.

**Comment by Ohmstyle64** [comment]
I think putting a colored spotlight on the ship would be easier than creating new models? The color could be based on the shipOwnership variable that lives in the ShipScript.

Unless, you think we should have nicer looking ship models? I am happy with the ones we have.

**Comment by yiochen** [comment]
I was thinking of creating new material and reuse the same mesh

**Comment by Ohmstyle64** [comment]
makes sense
