### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#63]
I don't know if we want to have different music for each of the following scenes:

1. Game Levels.
2. Next Transition.
3. Menu.

**Comment by yiochen** [comment]
I think the music is the smallest part. I would say just one single music for through out the whole game. but different sound effects for different events

**Comment by yiochen** [comment]
For this and sound effect, we should try to find some resource in asset store

**Comment by Ohmstyle64** [comment]
@yiochen  What do you think of the background music that I added? I also supplied 2 other choices but I felt they were too fast paced.

**Comment by yiochen** [comment]
I like the current one. It actually fits our game very well. Hope it doesn't have copy right lol
