### ISSUE TITLE
simplify soldier creation

### ISSUE THREAD

**Issue by yiochen** [yiochen/CSE381#66]
since we decided to remove the engineer, we only need to create soldier. It feels to me that is is an extra step to toggle the build soldier button on a new planet, since this is such a common thing to do, and it's hard to keep track of which planet is toggled (AI has advantage than human on this). What if we make it like the resource planet. As long as you own this soldier/hybrid planet, it will train soldiers automatically. 
 
This introduces a new problem however, the resource might go down without player doing anything. But we don't have any indication in our current game that resource is directly linked with soldiers, either.

**Comment by yiochen** [comment]
Um. Nevermind. I think it's better to leave the soldier toggle there. Later on, we will have more different kinds of planets(in theory, we will), and each planet has different actions for user to take, we cannot just default anything. But there should be some visual indication for planet that is creating unit, as well as planet that is generating resource

**Comment by Ohmstyle64** [comment]
I don't think we should remove the soldier toggle.

Now to make it more complicated....

I think we can use the resources for upgrades to soldier units. I already built a structure for upgrading soldiers in the SoldierUnit struct you will see defenseMod and attackMod. These mods are included in the CombatScript already as well. I'm thinking this would be an action that can only happen on Soldier planets and can take the place of the Engineer toggle.

Yes, we should have a visual indication. maybe a small animation like a soldier head with + signs floating up?

**Comment by yiochen** [comment]
I like the idea of soldier head popping up. but I don't think we want to add upgrade feature. As we see TA playing, this is a pretty fast pace game with a lot of stuff to keep track of. I think it would be too hard for user to remember to upgrade their unit

**Comment by Ohmstyle64** [comment]
The TA was mostly playing that fast because he didn't understand what was going on. When you play more strategically it slows down considerably.
I imagined the upgrade feature applying to all soldiers even if they were already trained. It would also be a high cost item.
My concern comes down to the useful and fun factor with the resources. If we can only spend it on training soldiers, I think that's kinda boring. Making your units more powerful sounds a bit more exciting.

**Comment by yiochen** [comment]
Yeah I agree that we should have more various ways of spending resource. What about a training planet. When player claims its ownership, they needs to click a button to activate it, and there will be a progress bar like the ship loading progress bar. Once it reaches maximum, your global soldier property level up by 1, then it will automatically reset the progress bar and start a second round of leveling up. If you lose the planet before it levels up, say 50%, you lose all your progress. Next time you take it back you have to start from 0% again.

**Comment by Ohmstyle64** [comment]
So what does increasing your global soldier property level do?

**Comment by yiochen** [comment]
I think instead of telling user the chose the attack , defence of soldiers to upgrade, we abstract it into levels. Say level one 50 attack, 100 defence, level 2 75 attack , 200 defence .

**Comment by Ohmstyle64** [comment]
Agreed, it's unnecessary to get into those details since it's a fast paced game.

I am imagining the resource expenditure for the upgrade happening all at once upfront. Say 100 resources for level , 150 level 2

**Comment by yiochen** [comment]
Yeah, when it starts a cycle of upgrading, resource is deducted, if it fails due to enemy attack, the resource will not be refunded
