### ISSUE TITLE
Resources Balancing

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#69]
Since we have infinite resources and they come continuously by owning a planet I am balancing the way resources are managed.

1. First, 2 Resource Planets are required to maintain continuous soldier production from a single Hybrid or Soldier Planet. This will be break-even and result in a 0 increase in resources every tick, adding a 3 resource planet will result in a net increase of resources with continuous soldier production. In #58  I implemented these changes.
2. Resource Collection on all planets globally should strictly happen **after** training units. This is to make sure that there is a consistent experience for collecting and spending resources. Also, this reinforces the idea that it's important to have 2 resource planets to maintain continuous soldier production.

**Comment by Ohmstyle64** [comment]
I changed PlanetScript to an abstract called AbstractPlanet and I implemented this abstract class for each of our planet types. The ultimate goal was to use the Script Execution Order settings, to ensure that Resources and Hybrid scripts were run last.

**Comment by yiochen** [comment]
It might be easier to separate the resource gathering and soldier training into two components, and controller the order of their updates being called. https://docs.unity3d.com/Manual/class-ScriptExecution.html
