### ISSUE TITLE
Animation Failed to Unload

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#99]
@yiochen  I'm getting an error with the animations failing to unload. Did all the meta files get committed?

**Comment by yiochen** [comment]
Yes, I dont have uncommited changes in my end. Which scene has that problem?

**Comment by Ohmstyle64** [comment]
Huh, really odd.. The issue went away when I closed down unity and reloaded. I don't know what happened. I will close this for now.
